### ISSUE TITLE
"0x0" is not supported as PedersenArg

### ISSUE THREAD

**Issue by dhruvkelawala** [paulmillr/micro-starknet#1]
While integrating this lib in starknet.js, I found a minor issue which I think should be rectified. 

In the function [pedersenArg()](https://github.com/paulmillr/micro-starknet/blob/0a3d722a2237618f4fffa62ee948ac0d511dde36/index.ts#L1256), if 0 is passed as a `bigInt` or `number`, it is returned as 0 or 0n. However, if 0 is passed as a hex string "0x0", it goes into [normalizeScalar()](https://github.com/paulmillr/micro-starknet/blob/0a3d722a2237618f4fffa62ee948ac0d511dde36/index.ts#L696) and throws `TypeError` because (parsed) 0 is not less than 0.

## Why is this important?

The function [compute_hash_on_elements](https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/cairo/common/hash_state.py#L6) is initialised with a 0 and we wish to pass all the values as Hex string including 0.

## Proposed Solution

1. The easiest solution would be adding `if (typeof arg === 'string' && hexToNumber(arg) === 0n) return 0n;` [here](https://github.com/paulmillr/micro-starknet/blob/0a3d722a2237618f4fffa62ee948ac0d511dde36/index.ts#L1258).

2. Add `computeHashOnElements` function in this lib which ensures that's its always initialised with 0 (or 0n) and just pass the elements as `Hex[] ` or (`PedersenArg[]`)

**Comment by paulmillr** [comment]
fixed in 074f418
